server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: location_service_route
          uri: lb://location-service
          predicates:
            - Path=/admin/locations/**, /locations/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
        - id: categories_service_route
          uri: lb://categories-service
          predicates:
            - Path=/admin/categories/**, /categories/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false