server:
  port: 0
stats:
  server:
    url: http://stats-server:9090
spring:
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
  sql:
    init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm-main
    username: root
    password: root
