create TABLE IF NOT EXISTS participation_requests (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	requester_id BIGINT NOT NULL,
	event_id BIGINT NOT NULL,
	status VARCHAR(9) NOT NULL,
	created TIMESTAMP NOT NULL,
	CONSTRAINT pk_participation_requests PRIMARY KEY (id),
	CONSTRAINT unique_participation_requests_requester_id_event_id UNIQUE (requester_id, event_id)
);