create TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id),
    CONSTRAINT categories_unique UNIQUE (name)
);

CREATE TABLE IF NOT exists events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    annotation         varchar(2000) NOT NULL,
    category_id        BIGINT        NOT NULL,
    initiator_id       BIGINT        NOT NULL,
    location_id        BIGINT        NOT NULL,
    paid               BOOL          NOT NULL,
    request_moderation BOOL          NOT NULL,
    title              varchar(120)  NOT NULL,
    state              varchar(9)    NOT NULL,
    description        varchar(7000) NOT NULL,
    event_date         timestamp     NOT NULL,
    participant_limit  INTEGER       NOT NULL,
    created_on         timestamp     NOT NULL,
    published_on       timestamp,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT events_category_id_fk FOREIGN KEY (category_id) REFERENCES categories (id)
);


CREATE TABLE IF NOT EXISTS compilations
(
    id     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  varchar(50)                             NOT NULL,
    pinned boolean                                 NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id bigint NOT NULL,
    event_id       bigint NOT NULL,
    CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT compilations_fk FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT events_fk FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);

