create TABLE IF NOT EXISTS categories (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                          name VARCHAR(50) NOT NULL,
                                          CONSTRAINT pk_stats PRIMARY KEY (id),
                                          CONSTRAINT categories_unique UNIQUE (name)
);
