server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
  sql:
    init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/location-service
    username: root
    password: root